name: flutter_tagging
description: A flutter package with tagging or multiselect functionality. Useful for adding Tag or Label Selection Forms.
version: 1.1.0
author: Sarbagya Dhaubanjar <mail@sarbagyastha.com.np>
homepage: https://github.com/sarbagyastha/flutter_tagging

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

